version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    env_file:
      - backend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "5172:5172"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    environment:
      - NODE_ENV=production
